<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MapStudio.Desktop</RootNamespace>
    <AssemblyName>OMSI Map Studio</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MapStudio.Core/MapStudio.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../MapStudio.UI/dist/**"
             Link="ui/%(RecursiveDir)%(Filename)%(Extension)"
             Condition="Exists('../MapStudio.UI/dist')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
