<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MapStudio.Native</RootNamespace>
    <ApplicationIcon>..\MapStudio.Desktop\Assets\MapStudio.ico</ApplicationIcon>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../MapStudio.Desktop/Assets/MapStudio.ico"
             Link="Assets\MapStudio.ico"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageReference Include="NSec.Cryptography" Version="26.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MapStudio.Core/MapStudio.Core.csproj" />
    <ProjectReference Include="../MapStudio.Renderer/MapStudio.Renderer.csproj" />
  </ItemGroup>

  <Target Name="MapStudioAddProjectPriToPublish"
          BeforeTargets="ComputeResolvedFilesToPublishList"
          DependsOnTargets="$(GenerateProjectPriFile)">
    <ItemGroup>
      <ResolvedFileToPublish Include="$(ProjectPriFullPath)"
                             Condition="'$(ProjectPriFullPath)' != '' And Exists('$(ProjectPriFullPath)')">
        <RelativePath>$(ProjectPriFileName)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
